In [74]:
%matplotlib inline

import os
import pandas as pd 
import numpy as np
import seaborn as sns
import datetime as dt
import matplotlib as mpl
from matplotlib import pyplot as plt
from xgboost import plot_importance
from sklearn.metrics import roc_auc_score
from collections import Counter
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import StratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
import lightgbm as LGB
from xgboost import XGBClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB


from IPython.display import display
import warnings
warnings.filterwarnings('ignore')


mpl.rc("figure", figsize=(100, 70))
mpl.rcParams.update({'font.size':25})

pd.set_option('display.max_columns', 500)

# Loading data

In [87]:
merged_data = pd.read_csv("../data/train/merged_data_after_feature_engineering.csv")

## Separating the train test features

In [88]:
train = merged_data[merged_data.is_test ==0]
test = merged_data[merged_data.is_test ==1]

train['redemption_status'] =train['redemption_status'].astype('int64')
train

,campaign_id,coupon_id,customer_id,id,is_test,redemption_status,campaign_type,campaign_start_date,campaign_end_date,coupon_available_on_item_ids,customer_age_range,customer_marital_status,is_customer_rented,customer_family_size,customer_no_of_children,customer_income_bracket,is_common_demographic_info_available_for_customer,no_of_items_coupon_is_available_for,is_coupon_available_for_multiple_item_ids,no_of_categories_of_items_available_under_coupon,coupon_available_on_category_1,coupon_available_on_category_2,coupon_available_on_brand_1,coupon_available_on_brand_2,coupon_more_focussed_on_brand_type,popularity_of_category1,popularity_of_category2,popularity_of_brand1,popularity_of_brand2,mean_discount_on_category1,mean_discount_on_category2,mean_discount_on_brand1,mean_discount_on_brand2,no_of_times_customer_bought_category1,no_of_times_customer_bought_category2,no_of_times_customer_bought_brand1,no_of_times_customer_bought_brand2,no_of_times_customer_bought_category1_in_discount,no_of_times_customer_bought_category2_in_discount,no_of_times_customer_bought_brand1_in_discount,no_of_times_customer_bought_brand2_in_discount,has_customer_ever_bought_category1,has_customer_ever_bought_category2,has_customer_ever_bought_brand1,has_customer_ever_bought_brand2,has_customer_ever_bought_category1_in_discount,has_customer_ever_bought_category2_in_discount,has_customer_ever_bought_brand1_in_discount,has_customer_ever_bought_brand2_in_discount,average_selling_price_per_unit_of_category1_brand1_combination,average_selling_price_per_unit_of_category2_brand2_combination,average_transaction_amount_for_customer_per_item_of_category1,average_transaction_amount_for_customer_per_item_of_category2,is_customers_spending_habit_on_category1_in_favour_of_category1_brand1_combo,is_customers_spending_habit_on_category1_in_favour_of_category2_brand2_combo,campaign_duration_in_days,was_user_active_during_campaign_period,does_user_significantly_prefer_focussed_brand_type,does_user_prefer_category1_from_brand1,does_user_prefer_category1_from_brand2,does_user_prefer_any_of_brand1_brand2_for_category1,total_spends_of_customer,total_spends_category_of_customer,total_coupon_discount_claimed_by_customer,coupon_claiming_category_of_customer,most_bought_category_of_user,is_coupon_category1_same_as_customer_most_bought_category,is_brand1_same_as_most_favourite_brand_of_user_in_category1,is_brand2_same_as_second_most_favourite_brand_of_user_in_category1,is_brand2_same_as_most_favourite_brand_of_user_in_category1,is_brand1_same_as_second_most_favourite_brand_of_user_in_category1,are_the_brands_customers_favourite_brands_for_category1
50226,13,27,1053,1,0,0,0,2013-05-19,2013-07-05,"38088,40251,38591,36817,56951,40715,38374,3960...",4,0,0.0,1,0,5.0,1,124,1,1,3,0,1105,1636,0,0.711382,0.0,0.003298,0.001451,22.507003,0.0,61.319363,70.109160,214,0,0,0,103,0,0,0,1,0,0,0,1,0,0,0,75.475914,-1.0,68.848024,0.0,0,1,47,1,0,0,0,0,57120.75,1,89.05,2,1,1,0,0,0,0,0
50227,13,116,48,2,0,0,0,2013-05-19,2013-07-05,"36721,39581,4157",3,1,0.0,2,0,3.0,1,2,1,1,3,0,56,-1,1,0.711382,0.0,0.264804,0.000000,22.507003,0.0,18.967506,0.000000,238,0,91,0,160,0,59,0,1,0,1,0,1,0,1,0,50.601550,-1.0,63.827453,0.0,1,1,47,1,0,1,0,1,90185.10,2,1237.79,4,1,1,1,0,0,0,1
50228,9,635,205,6,0,0,1,2013-03-11,2013-04-12,"12028,23534,28856,30989,27428,36001,12779,1341...",4,1,0.0,2,0,7.0,1,66,1,1,6,0,560,-1,0,0.117204,0.0,0.000129,0.000000,11.490816,0.0,47.960747,0.000000,86,0,0,0,23,0,0,0,1,0,0,0,1,0,0,0,233.863843,-1.0,127.284608,0.0,0,1,32,1,1,0,0,0,117461.66,3,2145.72,5,1,0,0,0,0,0,0
50229,13,644,1050,7,0,0,0,2013-05-19,2013-07-05,"45243,56946,65962,12342",-1,-1,-1.0,-1,-1,-1.0,0,3,1,1,3,0,611,-1,0,0.711382,0.0,0.000390,0.000000,22.507003,0.0,16.618030,0.000000,185,0,0,0,99,0,0,0,1,0,0,0,1,0,0,0,74.420565,-1.0,68.157042,0.0,0,1,47,1,0,0,0,0,23291.42,1,178.10,2,1,1,0,0,0,0,0
50230,8,1017,1489,9,0,0,0,2013-02-16,2013-04-05,"5969,48167,43567,13440,1996,6538,51029,48640,1...",4,1,0.0,2,0,3.0,1,31,1,1,3,0,1558,-1,0,0.711382,0.0,0.002604,0.000000,22.507003,0.0,24.645294,0.000000,404,0,0,0,205,0,0,0,1,0,0,0,1,0,0,0,146.231028,-1.0,47.515457,0.0,0,1,48,1,1,0,0,0,67797.49,2,265.01,3,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128590,8,71,1523,128587,0,0,0,2013-02-16,2013-04-05,"17029,1657,30155,12762",6,1,0.0,2,0,1.0,1,3,1,1,3,0,56,-1,1,0.711382,0.0,0.264804,0.000000,22.507003,0.0,18.967506,0.000000,173,0,50,0,91,0,25,0,1,0,1,0,1,0,1,0,50.601550,-1.0,89.835000,0.0,1,1,48,1,0,0,0,0,53058.23,1,0.00,0,1,1,1,0,0,0,1
128591,30,547,937,128589,0,0,0,2012-11-19,2013-01-04,"2596,18777,53061,42386,43044,3318,39336",6,1,0.0,2,0,2.0,1,6,1,1,3,0,2188,2179,0,0.711382,0.0,0.000989,0.000000,22.507003,0.0,10.752388,49.284644,165,0,0,0,84,0,0,0,1,0,0,0,1,0,0,0,97.851208,-1.0,61.067310,0.0,0,1,46,1,0,0,0,0,22570.47,1,89.05,2,1,1,0,0,0,0,0
128592,8,754,1004,128590,0,0,0,2013-02-16,2013-04-05,"70460,70534,9060,27164,58588,20849,5608,24948,...",-1,-1,-1.0,-1,-1,-1.0,0,82,1,1,3,0,864,-1,0,0.711382,0.0,0.001802,0.000000,22.507003,0.0,61.623552,0.000000,1324,0,2,0,725,0,2,0,1,0,1,0,1,0,1,0,118.686482,-1.0,68.054327,0.0,0,1,48,1,1,0,0,0,195328.75,4,260.03,3,1,1,0,0,0,0,0
128593,13,134,71,128592,0,0,0,2013-05-19,2013-07-05,"62219,1357,38776,41148,32563,62457,4047",3,1,0.0,5,3,4.0,1,6,1,1,3,0,11,56,1,0.711382,0.0,0.000000,0.264804,22.507003,0.0,14.411116,18.967506,788,0,1,101,589,0,0,57,1,0,1,1,1,0,0,1,51.438845,-1.0,57.893748,0.0,1,1,47,1,0,0,0,0,81141.98,2,1325.04,4,1,1,0,0,1,0,1
128594,13,681,623,128595,0,0,0,2013-05-19,2013-07-05,"44676,33551,16298,28879,40280,18577,13290,7323...",-1,-1,-1.0,-1,-1,-1.0,0,29,1,1,3,0,686,-1,0,0.711382,0.0,0.015547,0.000000,22.507003,0.0,13.093350,0.000000,577,0,21,0,300,0,8,0,1,0,1,0,1,0,1,0,151.574370,-1.0,92.610992,0.0,0,1,47,1,1,0,0,0,108049.26,3,0.00,0,1,1,0,0,0,0,0

In [89]:
test.shape

(50226, 72)

In [90]:
columns_with_other_dtype = merged_data.select_dtypes(include=['object', 'datetime64[ns]']).columns
columns_with_numeric_dtype = merged_data.select_dtypes(exclude='object').columns
columns_with_numeric_dtype

Index(['campaign_id', 'coupon_id', 'customer_id', 'id', 'is_test',
       'redemption_status', 'campaign_type', 'customer_age_range',
       'customer_marital_status', 'is_customer_rented', 'customer_family_size',
       'customer_no_of_children', 'customer_income_bracket',
       'is_common_demographic_info_available_for_customer',
       'no_of_items_coupon_is_available_for',
       'is_coupon_available_for_multiple_item_ids',
       'no_of_categories_of_items_available_under_coupon',
       'coupon_available_on_category_1', 'coupon_available_on_category_2',
       'coupon_available_on_brand_1', 'coupon_available_on_brand_2',
       'coupon_more_focussed_on_brand_type', 'popularity_of_category1',
       'popularity_of_category2', 'popularity_of_brand1',
       'popularity_of_brand2', 'mean_discount_on_category1',
       'mean_discount_on_category2', 'mean_discount_on_brand1',
       'mean_discount_on_brand2', 'no_of_times_customer_bought_category1',
       'no_of_times_customer_bought_category2',
       'no_of_times_customer_bought_brand1',
       'no_of_times_customer_bought_brand2',
       'no_of_times_customer_bought_category1_in_discount',
       'no_of_times_customer_bought_category2_in_discount',
       'no_of_times_customer_bought_brand1_in_discount',
       'no_of_times_customer_bought_brand2_in_discount',
       'has_customer_ever_bought_category1',
       'has_customer_ever_bought_category2', 'has_customer_ever_bought_brand1',
       'has_customer_ever_bought_brand2',
       'has_customer_ever_bought_category1_in_discount',
       'has_customer_ever_bought_category2_in_discount',
       'has_customer_ever_bought_brand1_in_discount',
       'has_customer_ever_bought_brand2_in_discount',
       'average_selling_price_per_unit_of_category1_brand1_combination',
       'average_selling_price_per_unit_of_category2_brand2_combination',
       'average_transaction_amount_for_customer_per_item_of_category1',
       'average_transaction_amount_for_customer_per_item_of_category2',
       'is_customers_spending_habit_on_category1_in_favour_of_category1_brand1_combo',
       'is_customers_spending_habit_on_category1_in_favour_of_category2_brand2_combo',
       'campaign_duration_in_days', 'was_user_active_during_campaign_period',
       'does_user_significantly_prefer_focussed_brand_type',
       'does_user_prefer_category1_from_brand1',
       'does_user_prefer_category1_from_brand2',
       'does_user_prefer_any_of_brand1_brand2_for_category1',
       'total_spends_of_customer', 'total_spends_category_of_customer',
       'total_coupon_discount_claimed_by_customer',
       'coupon_claiming_category_of_customer', 'most_bought_category_of_user',
       'is_coupon_category1_same_as_customer_most_bought_category',
       'is_brand1_same_as_most_favourite_brand_of_user_in_category1',
       'is_brand2_same_as_second_most_favourite_brand_of_user_in_category1',
       'is_brand2_same_as_most_favourite_brand_of_user_in_category1',
       'is_brand1_same_as_second_most_favourite_brand_of_user_in_category1',
       'are_the_brands_customers_favourite_brands_for_category1'],
      dtype='object')

In [91]:
categorical_columns = columns_with_other_dtype.drop(labels=['campaign_start_date', 'campaign_end_date', 'coupon_available_on_item_ids'])
numerical_columns = columns_with_numeric_dtype.drop(labels=['coupon_id', 'customer_id', 'id'])
features = numerical_columns.append(categorical_columns)
features

Index(['campaign_id', 'is_test', 'redemption_status', 'campaign_type',
       'customer_age_range', 'customer_marital_status', 'is_customer_rented',
       'customer_family_size', 'customer_no_of_children',
       'customer_income_bracket',
       'is_common_demographic_info_available_for_customer',
       'no_of_items_coupon_is_available_for',
       'is_coupon_available_for_multiple_item_ids',
       'no_of_categories_of_items_available_under_coupon',
       'coupon_available_on_category_1', 'coupon_available_on_category_2',
       'coupon_available_on_brand_1', 'coupon_available_on_brand_2',
       'coupon_more_focussed_on_brand_type', 'popularity_of_category1',
       'popularity_of_category2', 'popularity_of_brand1',
       'popularity_of_brand2', 'mean_discount_on_category1',
       'mean_discount_on_category2', 'mean_discount_on_brand1',
       'mean_discount_on_brand2', 'no_of_times_customer_bought_category1',
       'no_of_times_customer_bought_category2',
       'no_of_times_customer_bought_brand1',
       'no_of_times_customer_bought_brand2',
       'no_of_times_customer_bought_category1_in_discount',
       'no_of_times_customer_bought_category2_in_discount',
       'no_of_times_customer_bought_brand1_in_discount',
       'no_of_times_customer_bought_brand2_in_discount',
       'has_customer_ever_bought_category1',
       'has_customer_ever_bought_category2', 'has_customer_ever_bought_brand1',
       'has_customer_ever_bought_brand2',
       'has_customer_ever_bought_category1_in_discount',
       'has_customer_ever_bought_category2_in_discount',
       'has_customer_ever_bought_brand1_in_discount',
       'has_customer_ever_bought_brand2_in_discount',
       'average_selling_price_per_unit_of_category1_brand1_combination',
       'average_selling_price_per_unit_of_category2_brand2_combination',
       'average_transaction_amount_for_customer_per_item_of_category1',
       'average_transaction_amount_for_customer_per_item_of_category2',
       'is_customers_spending_habit_on_category1_in_favour_of_category1_brand1_combo',
       'is_customers_spending_habit_on_category1_in_favour_of_category2_brand2_combo',
       'campaign_duration_in_days', 'was_user_active_during_campaign_period',
       'does_user_significantly_prefer_focussed_brand_type',
       'does_user_prefer_category1_from_brand1',
       'does_user_prefer_category1_from_brand2',
       'does_user_prefer_any_of_brand1_brand2_for_category1',
       'total_spends_of_customer', 'total_spends_category_of_customer',
       'total_coupon_discount_claimed_by_customer',
       'coupon_claiming_category_of_customer', 'most_bought_category_of_user',
       'is_coupon_category1_same_as_customer_most_bought_category',
       'is_brand1_same_as_most_favourite_brand_of_user_in_category1',
       'is_brand2_same_as_second_most_favourite_brand_of_user_in_category1',
       'is_brand2_same_as_most_favourite_brand_of_user_in_category1',
       'is_brand1_same_as_second_most_favourite_brand_of_user_in_category1',
       'are_the_brands_customers_favourite_brands_for_category1'],
      dtype='object')

In [92]:
features = features.drop(labels=['is_test', 'redemption_status'])

In [93]:
X = train[features]
Y = train['redemption_status']

skf = StratifiedKFold(n_splits=3)

In [94]:
X

,campaign_id,campaign_type,customer_age_range,customer_marital_status,is_customer_rented,customer_family_size,customer_no_of_children,customer_income_bracket,is_common_demographic_info_available_for_customer,no_of_items_coupon_is_available_for,is_coupon_available_for_multiple_item_ids,no_of_categories_of_items_available_under_coupon,coupon_available_on_category_1,coupon_available_on_category_2,coupon_available_on_brand_1,coupon_available_on_brand_2,coupon_more_focussed_on_brand_type,popularity_of_category1,popularity_of_category2,popularity_of_brand1,popularity_of_brand2,mean_discount_on_category1,mean_discount_on_category2,mean_discount_on_brand1,mean_discount_on_brand2,no_of_times_customer_bought_category1,no_of_times_customer_bought_category2,no_of_times_customer_bought_brand1,no_of_times_customer_bought_brand2,no_of_times_customer_bought_category1_in_discount,no_of_times_customer_bought_category2_in_discount,no_of_times_customer_bought_brand1_in_discount,no_of_times_customer_bought_brand2_in_discount,has_customer_ever_bought_category1,has_customer_ever_bought_category2,has_customer_ever_bought_brand1,has_customer_ever_bought_brand2,has_customer_ever_bought_category1_in_discount,has_customer_ever_bought_category2_in_discount,has_customer_ever_bought_brand1_in_discount,has_customer_ever_bought_brand2_in_discount,average_selling_price_per_unit_of_category1_brand1_combination,average_selling_price_per_unit_of_category2_brand2_combination,average_transaction_amount_for_customer_per_item_of_category1,average_transaction_amount_for_customer_per_item_of_category2,is_customers_spending_habit_on_category1_in_favour_of_category1_brand1_combo,is_customers_spending_habit_on_category1_in_favour_of_category2_brand2_combo,campaign_duration_in_days,was_user_active_during_campaign_period,does_user_significantly_prefer_focussed_brand_type,does_user_prefer_category1_from_brand1,does_user_prefer_category1_from_brand2,does_user_prefer_any_of_brand1_brand2_for_category1,total_spends_of_customer,total_spends_category_of_customer,total_coupon_discount_claimed_by_customer,coupon_claiming_category_of_customer,most_bought_category_of_user,is_coupon_category1_same_as_customer_most_bought_category,is_brand1_same_as_most_favourite_brand_of_user_in_category1,is_brand2_same_as_second_most_favourite_brand_of_user_in_category1,is_brand2_same_as_most_favourite_brand_of_user_in_category1,is_brand1_same_as_second_most_favourite_brand_of_user_in_category1,are_the_brands_customers_favourite_brands_for_category1
50226,13,0,4,0,0.0,1,0,5.0,1,124,1,1,3,0,1105,1636,0,0.711382,0.0,0.003298,0.001451,22.507003,0.0,61.319363,70.109160,214,0,0,0,103,0,0,0,1,0,0,0,1,0,0,0,75.475914,-1.0,68.848024,0.0,0,1,47,1,0,0,0,0,57120.75,1,89.05,2,1,1,0,0,0,0,0
50227,13,0,3,1,0.0,2,0,3.0,1,2,1,1,3,0,56,-1,1,0.711382,0.0,0.264804,0.000000,22.507003,0.0,18.967506,0.000000,238,0,91,0,160,0,59,0,1,0,1,0,1,0,1,0,50.601550,-1.0,63.827453,0.0,1,1,47,1,0,1,0,1,90185.10,2,1237.79,4,1,1,1,0,0,0,1
50228,9,1,4,1,0.0,2,0,7.0,1,66,1,1,6,0,560,-1,0,0.117204,0.0,0.000129,0.000000,11.490816,0.0,47.960747,0.000000,86,0,0,0,23,0,0,0,1,0,0,0,1,0,0,0,233.863843,-1.0,127.284608,0.0,0,1,32,1,1,0,0,0,117461.66,3,2145.72,5,1,0,0,0,0,0,0
50229,13,0,-1,-1,-1.0,-1,-1,-1.0,0,3,1,1,3,0,611,-1,0,0.711382,0.0,0.000390,0.000000,22.507003,0.0,16.618030,0.000000,185,0,0,0,99,0,0,0,1,0,0,0,1,0,0,0,74.420565,-1.0,68.157042,0.0,0,1,47,1,0,0,0,0,23291.42,1,178.10,2,1,1,0,0,0,0,0
50230,8,0,4,1,0.0,2,0,3.0,1,31,1,1,3,0,1558,-1,0,0.711382,0.0,0.002604,0.000000,22.507003,0.0,24.645294,0.000000,404,0,0,0,205,0,0,0,1,0,0,0,1,0,0,0,146.231028,-1.0,47.515457,0.0,0,1,48,1,1,0,0,0,67797.49,2,265.01,3,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128590,8,0,6,1,0.0,2,0,1.0,1,3,1,1,3,0,56,-1,1,0.711382,0.0,0.264804,0.000000,22.507003,0.0,18.967506,0.000000,173,0,50,0,91,0,25,0,1,0,1,0,1,0,1,0,50.601550,-1.0,89.835000,0.0,1,1,48,1,0,0,0,0,53058.23,1,0.00,0,1,1,1,0,0,0,1
128591,30,0,6,1,0.0,2,0,2.0,1,6,1,1,3,0,2188,2179,0,0.711382,0.0,0.000989,0.000000,22.507003,0.0,10.752388,49.284644,165,0,0,0,84,0,0,0,1,0,0,0,1,0,0,0,97.851208,-1.0,61.067310,0.0,0,1,46,1,0,0,0,0,22570.47,1,89.05,2,1,1,0,0,0,0,0
128592,8,0,-1,-1,-1.0,-1,-1,-1.0,0,82,1,1,3,0,864,-1,0,0.711382,0.0,0.001802,0.000000,22.507003,0.0,61.623552,0.000000,1324,0,2,0,725,0,2,0,1,0,1,0,1,0,1,0,118.686482,-1.0,68.054327,0.0,0,1,48,1,1,0,0,0,195328.75,4,260.03,3,1,1,0,0,0,0,0
128593,13,0,3,1,0.0,5,3,4.0,1,6,1,1,3,0,11,56,1,0.711382,0.0,0.000000,0.264804,22.507003,0.0,14.411116,18.967506,788,0,1,101,589,0,0,57,1,0,1,1,1,0,0,1,51.438845,-1.0,57.893748,0.0,1,1,47,1,0,0,0,0,81141.98,2,1325.04,4,1,1,0,0,1,0,1
128594,13,0,-1,-1,-1.0,-1,-1,-1.0,0,29,1,1,3,0,686,-1,0,0.711382,0.0,0.015547,0.000000,22.507003,0.0,13.093350,0.000000,577,0,21,0,300,0,8,0,1,0,1,0,1,0,1,0,151.574370,-1.0,92.610992,0.0,0,1,47,1,1,0,0,0,108049.26,3,0.00,0,1,1,0,0,0,0,0

In [123]:
meta_df = pd.DataFrame({'true_values': Y})
meta_df.reset_index(inplace=True)
meta_df

        index  true_values
0       50226            0
1       50227            0
2       50228            0
3       50229            0
4       50230            0
...       ...          ...
78364  128590            0
78365  128591            0
78366  128592            0
78367  128593            0
78368  128594            0

[78369 rows x 2 columns]

In [104]:
X

,campaign_id,campaign_type,customer_age_range,customer_marital_status,is_customer_rented,customer_family_size,customer_no_of_children,customer_income_bracket,is_common_demographic_info_available_for_customer,no_of_items_coupon_is_available_for,is_coupon_available_for_multiple_item_ids,no_of_categories_of_items_available_under_coupon,coupon_available_on_category_1,coupon_available_on_category_2,coupon_available_on_brand_1,coupon_available_on_brand_2,coupon_more_focussed_on_brand_type,popularity_of_category1,popularity_of_category2,popularity_of_brand1,popularity_of_brand2,mean_discount_on_category1,mean_discount_on_category2,mean_discount_on_brand1,mean_discount_on_brand2,no_of_times_customer_bought_category1,no_of_times_customer_bought_category2,no_of_times_customer_bought_brand1,no_of_times_customer_bought_brand2,no_of_times_customer_bought_category1_in_discount,no_of_times_customer_bought_category2_in_discount,no_of_times_customer_bought_brand1_in_discount,no_of_times_customer_bought_brand2_in_discount,has_customer_ever_bought_category1,has_customer_ever_bought_category2,has_customer_ever_bought_brand1,has_customer_ever_bought_brand2,has_customer_ever_bought_category1_in_discount,has_customer_ever_bought_category2_in_discount,has_customer_ever_bought_brand1_in_discount,has_customer_ever_bought_brand2_in_discount,average_selling_price_per_unit_of_category1_brand1_combination,average_selling_price_per_unit_of_category2_brand2_combination,average_transaction_amount_for_customer_per_item_of_category1,average_transaction_amount_for_customer_per_item_of_category2,is_customers_spending_habit_on_category1_in_favour_of_category1_brand1_combo,is_customers_spending_habit_on_category1_in_favour_of_category2_brand2_combo,campaign_duration_in_days,was_user_active_during_campaign_period,does_user_significantly_prefer_focussed_brand_type,does_user_prefer_category1_from_brand1,does_user_prefer_category1_from_brand2,does_user_prefer_any_of_brand1_brand2_for_category1,total_spends_of_customer,total_spends_category_of_customer,total_coupon_discount_claimed_by_customer,coupon_claiming_category_of_customer,most_bought_category_of_user,is_coupon_category1_same_as_customer_most_bought_category,is_brand1_same_as_most_favourite_brand_of_user_in_category1,is_brand2_same_as_second_most_favourite_brand_of_user_in_category1,is_brand2_same_as_most_favourite_brand_of_user_in_category1,is_brand1_same_as_second_most_favourite_brand_of_user_in_category1,are_the_brands_customers_favourite_brands_for_category1
50226,13,0,4,0,0.0,1,0,5.0,1,124,1,1,3,0,1105,1636,0,0.711382,0.0,0.003298,0.001451,22.507003,0.0,61.319363,70.109160,214,0,0,0,103,0,0,0,1,0,0,0,1,0,0,0,75.475914,-1.0,68.848024,0.0,0,1,47,1,0,0,0,0,57120.75,1,89.05,2,1,1,0,0,0,0,0
50227,13,0,3,1,0.0,2,0,3.0,1,2,1,1,3,0,56,-1,1,0.711382,0.0,0.264804,0.000000,22.507003,0.0,18.967506,0.000000,238,0,91,0,160,0,59,0,1,0,1,0,1,0,1,0,50.601550,-1.0,63.827453,0.0,1,1,47,1,0,1,0,1,90185.10,2,1237.79,4,1,1,1,0,0,0,1
50228,9,1,4,1,0.0,2,0,7.0,1,66,1,1,6,0,560,-1,0,0.117204,0.0,0.000129,0.000000,11.490816,0.0,47.960747,0.000000,86,0,0,0,23,0,0,0,1,0,0,0,1,0,0,0,233.863843,-1.0,127.284608,0.0,0,1,32,1,1,0,0,0,117461.66,3,2145.72,5,1,0,0,0,0,0,0
50229,13,0,-1,-1,-1.0,-1,-1,-1.0,0,3,1,1,3,0,611,-1,0,0.711382,0.0,0.000390,0.000000,22.507003,0.0,16.618030,0.000000,185,0,0,0,99,0,0,0,1,0,0,0,1,0,0,0,74.420565,-1.0,68.157042,0.0,0,1,47,1,0,0,0,0,23291.42,1,178.10,2,1,1,0,0,0,0,0
50230,8,0,4,1,0.0,2,0,3.0,1,31,1,1,3,0,1558,-1,0,0.711382,0.0,0.002604,0.000000,22.507003,0.0,24.645294,0.000000,404,0,0,0,205,0,0,0,1,0,0,0,1,0,0,0,146.231028,-1.0,47.515457,0.0,0,1,48,1,1,0,0,0,67797.49,2,265.01,3,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128590,8,0,6,1,0.0,2,0,1.0,1,3,1,1,3,0,56,-1,1,0.711382,0.0,0.264804,0.000000,22.507003,0.0,18.967506,0.000000,173,0,50,0,91,0,25,0,1,0,1,0,1,0,1,0,50.601550,-1.0,89.835000,0.0,1,1,48,1,0,0,0,0,53058.23,1,0.00,0,1,1,1,0,0,0,1
128591,30,0,6,1,0.0,2,0,2.0,1,6,1,1,3,0,2188,2179,0,0.711382,0.0,0.000989,0.000000,22.507003,0.0,10.752388,49.284644,165,0,0,0,84,0,0,0,1,0,0,0,1,0,0,0,97.851208,-1.0,61.067310,0.0,0,1,46,1,0,0,0,0,22570.47,1,89.05,2,1,1,0,0,0,0,0
128592,8,0,-1,-1,-1.0,-1,-1,-1.0,0,82,1,1,3,0,864,-1,0,0.711382,0.0,0.001802,0.000000,22.507003,0.0,61.623552,0.000000,1324,0,2,0,725,0,2,0,1,0,1,0,1,0,1,0,118.686482,-1.0,68.054327,0.0,0,1,48,1,1,0,0,0,195328.75,4,260.03,3,1,1,0,0,0,0,0
128593,13,0,3,1,0.0,5,3,4.0,1,6,1,1,3,0,11,56,1,0.711382,0.0,0.000000,0.264804,22.507003,0.0,14.411116,18.967506,788,0,1,101,589,0,0,57,1,0,1,1,1,0,0,1,51.438845,-1.0,57.893748,0.0,1,1,47,1,0,0,0,0,81141.98,2,1325.04,4,1,1,0,0,1,0,1
128594,13,0,-1,-1,-1.0,-1,-1,-1.0,0,29,1,1,3,0,686,-1,0,0.711382,0.0,0.015547,0.000000,22.507003,0.0,13.093350,0.000000,577,0,21,0,300,0,8,0,1,0,1,0,1,0,1,0,151.574370,-1.0,92.610992,0.0,0,1,47,1,1,0,0,0,108049.26,3,0.00,0,1,1,0,0,0,0,0

In [105]:
test

,campaign_id,coupon_id,customer_id,id,is_test,redemption_status,campaign_type,campaign_start_date,campaign_end_date,coupon_available_on_item_ids,customer_age_range,customer_marital_status,is_customer_rented,customer_family_size,customer_no_of_children,customer_income_bracket,is_common_demographic_info_available_for_customer,no_of_items_coupon_is_available_for,is_coupon_available_for_multiple_item_ids,no_of_categories_of_items_available_under_coupon,coupon_available_on_category_1,coupon_available_on_category_2,coupon_available_on_brand_1,coupon_available_on_brand_2,coupon_more_focussed_on_brand_type,popularity_of_category1,popularity_of_category2,popularity_of_brand1,popularity_of_brand2,mean_discount_on_category1,mean_discount_on_category2,mean_discount_on_brand1,mean_discount_on_brand2,no_of_times_customer_bought_category1,no_of_times_customer_bought_category2,no_of_times_customer_bought_brand1,no_of_times_customer_bought_brand2,no_of_times_customer_bought_category1_in_discount,no_of_times_customer_bought_category2_in_discount,no_of_times_customer_bought_brand1_in_discount,no_of_times_customer_bought_brand2_in_discount,has_customer_ever_bought_category1,has_customer_ever_bought_category2,has_customer_ever_bought_brand1,has_customer_ever_bought_brand2,has_customer_ever_bought_category1_in_discount,has_customer_ever_bought_category2_in_discount,has_customer_ever_bought_brand1_in_discount,has_customer_ever_bought_brand2_in_discount,average_selling_price_per_unit_of_category1_brand1_combination,average_selling_price_per_unit_of_category2_brand2_combination,average_transaction_amount_for_customer_per_item_of_category1,average_transaction_amount_for_customer_per_item_of_category2,is_customers_spending_habit_on_category1_in_favour_of_category1_brand1_combo,is_customers_spending_habit_on_category1_in_favour_of_category2_brand2_combo,campaign_duration_in_days,was_user_active_during_campaign_period,does_user_significantly_prefer_focussed_brand_type,does_user_prefer_category1_from_brand1,does_user_prefer_category1_from_brand2,does_user_prefer_any_of_brand1_brand2_for_category1,total_spends_of_customer,total_spends_category_of_customer,total_coupon_discount_claimed_by_customer,coupon_claiming_category_of_customer,most_bought_category_of_user,is_coupon_category1_same_as_customer_most_bought_category,is_brand1_same_as_most_favourite_brand_of_user_in_category1,is_brand2_same_as_second_most_favourite_brand_of_user_in_category1,is_brand2_same_as_most_favourite_brand_of_user_in_category1,is_brand1_same_as_second_most_favourite_brand_of_user_in_category1,are_the_brands_customers_favourite_brands_for_category1
0,22,869,967,3,1,1.125965e-06,0,2013-09-16,2013-10-18,"1124,1185,39835,46911,3514,1033,45271,56179,40...",3,0,0.0,1,0,5.0,1,71,1,1,3,0,1075,-1,0,0.711382,0.000000,0.003300,0.000000,22.507003,0.000000,37.102000,0.000000,980,0,15,0,543,0,14,0,1,0,1,0,1,0,1,0,108.805335,-1.0,90.982959,0.000000,0,1,32,0,1,0,0,0,156733.77,4,2111.86,5,1,1,0,0,0,0,0
1,20,389,1566,4,1,9.004924e-12,1,2013-09-07,2013-11-16,"47705,45063,19431,56517,1479,68534,56523,1144,...",2,1,0.0,2,0,9.0,1,32,1,1,6,0,57,1009,0,0.117204,0.000000,0.001626,0.000304,11.490816,0.000000,17.556861,13.948629,622,0,11,0,123,0,3,0,1,0,1,0,1,0,1,0,134.793144,-1.0,103.423798,0.000000,0,1,70,0,1,0,0,0,297070.87,5,1489.97,4,1,0,0,0,0,0,0
2,22,981,510,5,1,4.206358e-12,0,2013-09-16,2013-10-18,"1690,7061,58004,22631,6577,2398,41769,21773,33...",2,1,0.0,2,1,1.0,1,18,1,1,3,0,1335,-1,0,0.711382,0.000000,0.000987,0.000000,22.507003,0.000000,17.113015,0.000000,1236,0,0,0,700,0,0,0,1,0,0,0,1,0,0,0,79.543017,-1.0,55.211986,0.000000,0,1,32,0,1,0,0,0,161811.27,4,2384.75,5,1,1,0,0,0,0,0
3,25,1069,361,8,1,1.582804e-19,1,2013-10-21,2013-11-22,"10284,70009,57994,11281,44510,35356,29737,6994...",1,0,0.0,1,0,3.0,1,73,1,1,3,0,1996,-1,0,0.711382,0.000000,0.002861,0.000000,22.507003,0.000000,58.302656,0.000000,454,0,0,0,204,0,0,0,1,0,0,0,1,0,0,0,99.960960,-1.0,58.620148,0.000000,0,1,32,0,0,0,0,0,49149.16,1,0.00,0,1,1,0,0,0,0,0
4,17,498,811,10,1,2.309650e-17,1,2013-07-29,2013-08-30,"45021,54805,14259,37463,48668,16481,4078,19852...",-1,-1,-1.0,-1,-1,-1.0,0,17,1,1,3,0,209,-1,0,0.711382,0.000000,0.006342,0.000000,22.507003,0.000000,21.023715,0.000000,994,0,8,0,484,0,5,0,1,0,1,0,1,0,1,0,68.246478,-1.0,52.986002,0.000000,0,1,32,0,0,0,0,0,117044.09,3,89.04,2,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50221,20,843,501,128584,1,1.002447e-12,1,2013-09-07,2013-11-16,"66094,66031,65895,65905,73540,65894,66078,65854",4,0,0.0,1,0,5.0,1,7,1,1,3,0,1009,57,0,0.711382,0.000000,0.000304,0.001626,22.507003,0.000000,13.948629,17.556861,1219,0,6,7,840,0,5,5,1,0,1,1,1,0,1,1,141.539074,-1.0,61.246401,0.000000,0,1,70,0,1,0,0,0,154702.14,4,241.85,3,1,1,0,0,0,0,0
50222,25,415,481,128588,1,1.226719e-10,1,2013-10-21,2013-11-22,"53917,38541,53519,44431,47604,37040,23296,1619...",3,1,1.0,4,2,2.0,1,106,1,1,3,0,89,-1,0,0.711382,0.000000,0.017482,0.000000,22.507003,0.000000,38.099900,0.000000,1600,0,79,0,659,0,73,0,1,0,1,0,1,0,1,0,82.935282,-1.0,44.249305,0.000000,0,1,32,0,0,0,0,0,111537.83,3,1354.98,4,1,1,0,1,0,1,1
50223,25,596,1336,128591,1,9.993779e-14,1,2013-10-21,2013-11-22,"3556,48890,42515,105,44440,1001,36451,46855,68...",3,1,0.0,5,3,9.0,1,68,1,2,3,1,487,-1,0,0.711382,0.015450,0.023221,0.000000,22.507003,15.867442,14.869981,0.000000,1573,3,87,0,874,2,38,0,1,1,1,0,1,1,1,0,61.157145,-1.0,80.561195,112.676667,1,1,32,0,1,0,0,0,331724.69,5,5195.86,5,1,1,0,1,0,1,1
50224,22,518,748,128593,1,4.051403e-09,0,2013-09-16,2013-10-18,"34936,44407,42927,3264,3544,979,65282,23340,14...",4,1,0.0,3,1,8.0,1,69,1,1,3,0,278,-1,0,0.711382,0.000000,0.018100,0.000000,22.507003,0.000000,24.820366,0.000000,1810,0,24,0,1159,0,16,0,1,0,1,0,1,0,1,0,72.980151,-1.0,71.128754,0.000000,0,1,32,0,1,0,0,0,308723.95,5,10752.81,5,1,1,0,0,0,0,0
50225,18,988,851,128594,1,2.274088e-88,0,2013-08-10,2013-10-04,"10964,27316,62840,25905,28460,25990,6081,29489...",3,1,0.0,2,0,6.0,1,59,1,2,6,8,1342,-1,0,0.117204,0.003675,0.000273,0.000000,11.490816,26.034393,8.965419,0.000000,69,0,0,0,8,0,0,0,1,0,0,0,1,0,0,0,229.632683,-1.0,112.355000,0.000000,0,1,55,0,1,0,0,0,129479.39,3,55.21,2,1,0,0,0,0,0,0

# Training the final XGB

In [127]:
%%time

param_grid = {
    'n_estimators': [2000],
    'learning_rate': [0.3],
    'max_depth' : [3],
    'min_child_weight' : [0.5]
    
}
xgb = XGBClassifier(objective='binary:logistic', nthreads= -1, seed=27, verbosity=2)

clf = GridSearchCV(xgb, param_grid=param_grid, cv=skf, n_jobs=-1, verbose=3, scoring='roc_auc').fit(X, Y)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] learning_rate=0.3, max_depth=3, min_child_weight=0.5, n_estimators=2000
[CV] learning_rate=0.3, max_depth=3, min_child_weight=0.5, n_estimators=2000
[CV] learning_rate=0.3, max_depth=3, min_child_weight=0.5, n_estimators=2000
[CV]  learning_rate=0.3, max_depth=3, min_child_weight=0.5, n_estimators=2000, score=0.9675351098135745, total= 9.8min
[CV]  learning_rate=0.3, max_depth=3, min_child_weight=0.5, n_estimators=2000, score=0.9685485717556815, total= 9.8min
[CV]  learning_rate=0.3, max_depth=3, min_child_weight=0.5, n_estimators=2000, score=0.9674386691345304, total= 9.9min

[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed: 10.0min finished

CPU times: user 8min 55s, sys: 1.17 s, total: 8min 56s
Wall time: 19min 16s

In [128]:
roc_auc_score( Y.values,clf.predict_proba((X))[:,1])

0.9999997791502265

In [129]:
sum(clf.predict(test[features]))

119

### Saving the submission

In [130]:
c='final'
test['redemption_status'] =clf.predict_proba(test[features])[:,1]
submission = test.loc[:,['id', 'redemption_status']]
name = "../data/submissions/submission_after_modeling_xgb"+str(c)+".csv"
submission.to_csv( name,index=False)
print("File saved!")

meta_df['xgb']= pd.Series(clf.predict_proba(X)[:,1])
meta_df

File saved!

        index  true_values           xgb
0       50226            0  1.844130e-10
1       50227            0  2.950676e-09
2       50228            0  1.993357e-06
3       50229            0  1.845069e-07
4       50230            0  1.140619e-10
...       ...          ...           ...
78364  128590            0  1.029370e-10
78365  128591            0  4.358262e-10
78366  128592            0  1.796716e-04
78367  128593            0  2.526386e-08
78368  128594            0  6.396996e-05

[78369 rows x 3 columns]

# Training the final LGBM model

In [131]:
%%time


param_grid = {
    'n_estimators': [4000],
    'learning_rate': [0.2],
    'max_depth': [5],
    'min_data_in_leaf' : [5],
    'num_leaves': [30],
    'feature_fraction': [0.3],
    'drop_rate': [0.2]
    
}
lgbm = LGB.LGBMClassifier(objective='binary', nthreads=-1, seed=27, verbosity=2, is_imbalance=True, metric='auc')

clf = GridSearchCV(lgbm, param_grid=param_grid, cv=skf, n_jobs=-1, verbose=3, scoring='roc_auc').fit(X, Y)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] drop_rate=0.2, feature_fraction=0.3, learning_rate=0.2, max_depth=5, min_data_in_leaf=5, n_estimators=4000, num_leaves=30
[CV] drop_rate=0.2, feature_fraction=0.3, learning_rate=0.2, max_depth=5, min_data_in_leaf=5, n_estimators=4000, num_leaves=30
[CV] drop_rate=0.2, feature_fraction=0.3, learning_rate=0.2, max_depth=5, min_data_in_leaf=5, n_estimators=4000, num_leaves=30
[CV]  drop_rate=0.2, feature_fraction=0.3, learning_rate=0.2, max_depth=5, min_data_in_leaf=5, n_estimators=4000, num_leaves=30, score=0.9657913065048562, total= 2.3min
[CV]  drop_rate=0.2, feature_fraction=0.3, learning_rate=0.2, max_depth=5, min_data_in_leaf=5, n_estimators=4000, num_leaves=30, score=0.9581952315530369, total= 2.4min
[CV]  drop_rate=0.2, feature_fraction=0.3, learning_rate=0.2, max_depth=5, min_data_in_leaf=5, n_estimators=4000, num_leaves=30, score=0.9650720959668238, total= 2.5min

[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:  3.4min finished

CPU times: user 55.1 s, sys: 597 ms, total: 55.7 s
Wall time: 4min 19s

In [132]:
roc_auc_score( Y.values,clf.predict_proba((X))[:,1])

0.9999997791502265

In [133]:
sum(clf.predict(test[features]))

93

### Saving the submission

In [134]:
c='final'
test['redemption_status'] =clf.predict_proba(test[features])[:,1]
submission = test.loc[:,['id', 'redemption_status']]
name = "../data/submissions/submission_after_modeling_lgb_"+str(c)+".csv"
submission.to_csv( name,index=False)
print("File saved!")
test['redemption_status']

meta_df['lgbm']= pd.Series(clf.predict_proba(X)[:,1])
meta_df

File saved!

        index  true_values           xgb          lgbm
0       50226            0  1.844130e-10  7.593028e-21
1       50227            0  2.950676e-09  1.391444e-11
2       50228            0  1.993357e-06  4.043333e-12
3       50229            0  1.845069e-07  1.684121e-14
4       50230            0  1.140619e-10  1.686546e-18
...       ...          ...           ...           ...
78364  128590            0  1.029370e-10  3.171440e-18
78365  128591            0  4.358262e-10  1.939694e-21
78366  128592            0  1.796716e-04  3.769460e-12
78367  128593            0  2.526386e-08  1.526372e-15
78368  128594            0  6.396996e-05  5.632601e-10

[78369 rows x 4 columns]

# Training all weak models

### Training Log-reg

In [135]:
%%time
param_grid = {
    'C' : [1],
    'max_iter' : [500],
    'penalty': ['l1']
}

lr = LogisticRegression(verbose=2, random_state=27, class_weight='balanced')

clf = GridSearchCV(lr, param_grid=param_grid, cv=skf, n_jobs=-1, verbose=3, scoring='roc_auc').fit(X, Y)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] C=1, max_iter=500, penalty=l1 ...................................
[CV] C=1, max_iter=500, penalty=l1 ...................................
[CV] C=1, max_iter=500, penalty=l1 ...................................
[LibLinear][CV]  C=1, max_iter=500, penalty=l1, score=0.9425021943633485, total= 5.3min
[LibLinear][CV]  C=1, max_iter=500, penalty=l1, score=0.9486727281978872, total= 6.4min
[LibLinear][CV]  C=1, max_iter=500, penalty=l1, score=0.9467381901908778, total= 8.2min

[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:  8.2min finished

[LibLinear]CPU times: user 2min 6s, sys: 1.02 s, total: 2min 7s
Wall time: 10min 40s

In [136]:
roc_auc_score( Y.values,clf.predict_proba((X))[:,1])

0.9527666557831898

In [137]:
sum(clf.predict(test[features]))

921

### Saving the submission

In [140]:
c='final'
test['redemption_status'] =clf.predict_proba(test[features])[:,1]
submission = test.loc[:,['id', 'redemption_status']]
name = "../data/submissions/submission_after_modeling_log_reg_"+str(c)+".csv"
submission.to_csv( name,index=False)
print("File saved!")
test['redemption_status']

meta_df['log_reg']= pd.Series(clf.predict_proba(X)[:,1])
meta_df

File saved!

        index  true_values           xgb          lgbm   log_reg
0       50226            0  1.844130e-10  7.593028e-21  0.000094
1       50227            0  2.950676e-09  1.391444e-11  0.164427
2       50228            0  1.993357e-06  4.043333e-12  0.000510
3       50229            0  1.845069e-07  1.684121e-14  0.000118
4       50230            0  1.140619e-10  1.686546e-18  0.000500
...       ...          ...           ...           ...       ...
78364  128590            0  1.029370e-10  3.171440e-18  0.001063
78365  128591            0  4.358262e-10  1.939694e-21  0.000121
78366  128592            0  1.796716e-04  3.769460e-12  0.746243
78367  128593            0  2.526386e-08  1.526372e-15  0.000116
78368  128594            0  6.396996e-05  5.632601e-10  0.124805

[78369 rows x 5 columns]

### Training BernoulliNB

In [141]:
%%time
param_grid = {
    'alpha' : [0.001]
}

bnb = BernoulliNB()

clf = GridSearchCV(bnb, param_grid=param_grid, cv=skf, n_jobs=-1, verbose=3, scoring='roc_auc').fit(X, Y)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] alpha=0.001 .....................................................
[CV] alpha=0.001 .....................................................
[CV] alpha=0.001 .....................................................
[CV] ............ alpha=0.001, score=0.9002439241577143, total=   0.8s
[CV] ............ alpha=0.001, score=0.8992504182011309, total=   0.7s
[CV] ............ alpha=0.001, score=0.8795811310193931, total=   0.6s

[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    1.4s finished

CPU times: user 528 ms, sys: 209 ms, total: 737 ms
Wall time: 2.03 s

In [142]:
roc_auc_score( Y.values,clf.predict_proba((X))[:,1])

0.8945174750475092

In [143]:
sum(clf.predict(test[features]))

631

### Saving the submission

In [144]:
c='final'
test['redemption_status'] =clf.predict_proba(test[features])[:,1]
submission = test.loc[:,['id', 'redemption_status']]
name = "../data/submissions/submission_after_modeling_BernoulliNB_"+str(c)+".csv"
submission.to_csv( name,index=False)
print("File saved!")
test['redemption_status']

meta_df['BernoulliNB']= pd.Series(clf.predict_proba(X)[:,1])
meta_df

File saved!

        index  true_values           xgb          lgbm   log_reg   BernoulliNB
0       50226            0  1.844130e-10  7.593028e-21  0.000094  3.790405e-17
1       50227            0  2.950676e-09  1.391444e-11  0.164427  2.284324e-03
2       50228            0  1.993357e-06  4.043333e-12  0.000510  3.235741e-18
3       50229            0  1.845069e-07  1.684121e-14  0.000118  5.998099e-20
4       50230            0  1.140619e-10  1.686546e-18  0.000500  2.058991e-17
...       ...          ...           ...           ...       ...           ...
78364  128590            0  1.029370e-10  3.171440e-18  0.001063  4.970191e-13
78365  128591            0  4.358262e-10  1.939694e-21  0.000121  2.382791e-17
78366  128592            0  1.796716e-04  3.769460e-12  0.746243  5.622522e-03
78367  128593            0  2.526386e-08  1.526372e-15  0.000116  3.087304e-05
78368  128594            0  6.396996e-05  5.632601e-10  0.124805  2.913724e-13

[78369 rows x 6 columns]

### Training RF

In [145]:
%%time
param_grid = {
    'n_estimators' : [1500]
}

rf = RandomForestClassifier(oob_score =True,n_jobs = 1,random_state =1)

clf = GridSearchCV(rf, param_grid=param_grid, cv=skf, n_jobs=-1, verbose=3, scoring='roc_auc').fit(X, Y)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] n_estimators=1500 ...............................................
[CV] n_estimators=1500 ...............................................
[CV] n_estimators=1500 ...............................................
[CV] ...... n_estimators=1500, score=0.9674773885168012, total= 3.7min
[CV] ...... n_estimators=1500, score=0.9715703531970921, total= 3.7min
[CV] ...... n_estimators=1500, score=0.9639850910501779, total= 3.7min

[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:  4.0min finished

CPU times: user 3min 9s, sys: 3.74 s, total: 3min 13s
Wall time: 7min 18s

In [146]:
roc_auc_score( Y.values,clf.predict_proba((X))[:,1])

0.9999997791502266

In [147]:
sum(clf.predict(test[features]))

85

### Saving the submission

In [148]:
c='final'
test['redemption_status'] =clf.predict_proba(test[features])[:,1]
submission = test.loc[:,['id', 'redemption_status']]
name = "../data/submissions/submission_after_modeling_RF_"+str(c)+".csv"
submission.to_csv( name,index=False)
print("File saved!")
test['redemption_status']

meta_df['RF']= pd.Series(clf.predict_proba(X)[:,1])
meta_df

File saved!

,index,true_values,xgb,lgbm,log_reg,BernoulliNB,RF
0,50226,0,1.844130e-10,7.593028e-21,0.000094,3.790405e-17,0.000000
1,50227,0,2.950676e-09,1.391444e-11,0.164427,2.284324e-03,0.000000
2,50228,0,1.993357e-06,4.043333e-12,0.000510,3.235741e-18,0.000000
3,50229,0,1.845069e-07,1.684121e-14,0.000118,5.998099e-20,0.000000
4,50230,0,1.140619e-10,1.686546e-18,0.000500,2.058991e-17,0.000000
...,...,...,...,...,...,...,...
78364,128590,0,1.029370e-10,3.171440e-18,0.001063,4.970191e-13,0.000000
78365,128591,0,4.358262e-10,1.939694e-21,0.000121,2.382791e-17,0.000000
78366,128592,0,1.796716e-04,3.769460e-12,0.746243,5.622522e-03,0.008667
78367,128593,0,2.526386e-08,1.526372e-15,0.000116,3.087304e-05,0.000667
78368,128594,0,6.396996e-05,5.632601e-10,0.124805,2.913724e-13,0.002000

### Training Extra Trees

In [149]:
%%time
param_grid = {
    'n_estimators' : [1500],
    'max_features' : [9]
    
}

etc = ExtraTreesClassifier(oob_score =True, bootstrap=True,n_jobs = 1,random_state =1)

clf = GridSearchCV(etc, param_grid=param_grid, cv=skf, n_jobs=-1, verbose=3, scoring='roc_auc').fit(X, Y)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] max_features=9, n_estimators=1500 ...............................
[CV] max_features=9, n_estimators=1500 ...............................
[CV] max_features=9, n_estimators=1500 ...............................
[CV]  max_features=9, n_estimators=1500, score=0.9613867581302753, total= 3.0min
[CV]  max_features=9, n_estimators=1500, score=0.958669563862334, total= 3.0min
[CV]  max_features=9, n_estimators=1500, score=0.9638382436188548, total= 3.0min

[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:  3.4min finished

CPU times: user 2min 27s, sys: 4.95 s, total: 2min 32s
Wall time: 6min

In [150]:
roc_auc_score( Y.values,clf.predict_proba((X))[:,1])

0.9999997791502265

In [151]:
sum(clf.predict(test[features]))

52

### Saving the submission

In [152]:
c='final'
test['redemption_status'] =clf.predict_proba(test[features])[:,1]
submission = test.loc[:,['id', 'redemption_status']]
name = "../data/submissions/submission_after_modeling_ExtraTrees_"+str(c)+".csv"
submission.to_csv( name,index=False)
print("File saved!")
test['redemption_status']

meta_df['ExtraTrees']= pd.Series(clf.predict_proba(X)[:,1])
meta_df

File saved!

,index,true_values,xgb,lgbm,log_reg,BernoulliNB,RF,ExtraTrees
0,50226,0,1.844130e-10,7.593028e-21,0.000094,3.790405e-17,0.000000,0.000000
1,50227,0,2.950676e-09,1.391444e-11,0.164427,2.284324e-03,0.000000,0.000000
2,50228,0,1.993357e-06,4.043333e-12,0.000510,3.235741e-18,0.000000,0.000000
3,50229,0,1.845069e-07,1.684121e-14,0.000118,5.998099e-20,0.000000,0.000000
4,50230,0,1.140619e-10,1.686546e-18,0.000500,2.058991e-17,0.000000,0.000000
...,...,...,...,...,...,...,...,...
78364,128590,0,1.029370e-10,3.171440e-18,0.001063,4.970191e-13,0.000000,0.000000
78365,128591,0,4.358262e-10,1.939694e-21,0.000121,2.382791e-17,0.000000,0.000000
78366,128592,0,1.796716e-04,3.769460e-12,0.746243,5.622522e-03,0.008667,0.005333
78367,128593,0,2.526386e-08,1.526372e-15,0.000116,3.087304e-05,0.000667,0.002000
78368,128594,0,6.396996e-05,5.632601e-10,0.124805,2.913724e-13,0.002000,0.000000

# Ensembling all submissions

In [41]:
xgb = pd.read_csv("../data/submissions/submission_after_modeling_xgbfinal.csv")
lgbm = pd.read_csv("../data/submissions/submission_after_modeling_lgb_final.csv")
log_reg = pd.read_csv("../data/submissions/submission_after_modeling_log_reg_final.csv")
BernoulliNB = pd.read_csv("../data/submissions/submission_after_modeling_BernoulliNB_final.csv")
RF = pd.read_csv("../data/submissions/submission_after_modeling_RF_final.csv")
ExtraTrees = pd.read_csv("../data/submissions/submission_after_modeling_ExtraTrees_final.csv")

In [42]:
ensembled = xgb.copy()

In [44]:
ensembled['redemption_status'] = ensembled['redemption_status']*0.25
ensembled['redemption_status'] = ensembled['redemption_status']+lgbm['redemption_status']*0.25+log_reg['redemption_status']*0.1+BernoulliNB['redemption_status']*0.1+RF['redemption_status']*0.15+ExtraTrees['redemption_status']*0.15

In [45]:
ensembled

           id  redemption_status
0           3       1.418777e-01
1           4       9.894503e-03
2           5       1.581439e-04
3           8       1.589039e-08
4          10       9.403907e-04
...       ...                ...
50221  128584       1.488913e-02
50222  128588       5.398301e-02
50223  128591       1.855573e-01
50224  128593       8.906658e-02
50225  128594       3.129665e-07

[50226 rows x 2 columns]

### Saving the ensembled solution

In [46]:
c='final'
name = "../data/submissions/submission_after_ensembling_lgb_xgb_weak_learners"+str(c)+".csv"
ensembled.to_csv( name,index=False)
print("File saved!")

File saved!

# Generating a meta-model on top of these

In [153]:
meta_df_X = meta_df[['xgb', 'lgbm', 'log_reg', 'BernoulliNB', 'RF', 'ExtraTrees']]
meta_df_Y = meta_df.true_values

In [154]:
meta_df_X

,xgb,lgbm,log_reg,BernoulliNB,RF,ExtraTrees
0,1.844130e-10,7.593028e-21,0.000094,3.790405e-17,0.000000,0.000000
1,2.950676e-09,1.391444e-11,0.164427,2.284324e-03,0.000000,0.000000
2,1.993357e-06,4.043333e-12,0.000510,3.235741e-18,0.000000,0.000000
3,1.845069e-07,1.684121e-14,0.000118,5.998099e-20,0.000000,0.000000
4,1.140619e-10,1.686546e-18,0.000500,2.058991e-17,0.000000,0.000000
...,...,...,...,...,...,...
78364,1.029370e-10,3.171440e-18,0.001063,4.970191e-13,0.000000,0.000000
78365,4.358262e-10,1.939694e-21,0.000121,2.382791e-17,0.000000,0.000000
78366,1.796716e-04,3.769460e-12,0.746243,5.622522e-03,0.008667,0.005333
78367,2.526386e-08,1.526372e-15,0.000116,3.087304e-05,0.000667,0.002000
78368,6.396996e-05,5.632601e-10,0.124805,2.913724e-13,0.002000,0.000000

In [155]:
meta_df_Y

0        0
1        0
2        0
3        0
4        0
        ..
78364    0
78365    0
78366    0
78367    0
78368    0
Name: true_values, Length: 78369, dtype: int64

In [156]:
xgb = pd.read_csv("../data/submissions/submission_after_modeling_xgbfinal.csv")
lgbm = pd.read_csv("../data/submissions/submission_after_modeling_lgb_final.csv")
log_reg = pd.read_csv("../data/submissions/submission_after_modeling_log_reg_final.csv")
BernoulliNB = pd.read_csv("../data/submissions/submission_after_modeling_BernoulliNB_final.csv")
RF = pd.read_csv("../data/submissions/submission_after_modeling_RF_final.csv")
ExtraTrees = pd.read_csv("../data/submissions/submission_after_modeling_ExtraTrees_final.csv")


meta_df_test = xgb.copy()
meta_df_test['xgb'] = xgb['redemption_status']
meta_df_test['lgbm'] = lgbm['redemption_status']

meta_df_test['log_reg'] = log_reg['redemption_status']

meta_df_test['BernoulliNB'] = BernoulliNB['redemption_status']

meta_df_test['RF'] = RF['redemption_status']

meta_df_test['ExtraTrees'] = ExtraTrees['redemption_status']

In [157]:
meta_df_test

,id,redemption_status,xgb,lgbm,log_reg,BernoulliNB,RF,ExtraTrees
0,3,4.930832e-02,4.930832e-02,1.125965e-06,7.779146e-01,4.138573e-05,0.230000,0.176667
1,4,1.216368e-05,1.216368e-05,9.004924e-12,3.781057e-02,1.268509e-04,0.032667,0.008000
2,5,1.059312e-06,1.059312e-06,4.206358e-12,5.807765e-04,4.156605e-21,0.000000,0.000667
3,8,2.008840e-11,2.008840e-11,1.582804e-19,1.588913e-07,9.165213e-33,0.000000,0.000000
4,10,1.397163e-08,1.397163e-08,2.309650e-17,8.403802e-03,9.646834e-08,0.000000,0.000667
...,...,...,...,...,...,...,...,...
50221,128584,1.127315e-06,1.127315e-06,1.002447e-12,3.390835e-02,2.698223e-02,0.037333,0.021333
50222,128588,4.976915e-04,4.976915e-04,1.226719e-10,2.351223e-01,2.300839e-04,0.115444,0.087333
50223,128591,9.088521e-05,9.088521e-05,9.993779e-14,5.321311e-01,8.933855e-01,0.176667,0.110000
50224,128593,8.021926e-03,8.021926e-03,4.051403e-09,5.585079e-01,1.442393e-04,0.116667,0.101333
50225,128594,6.408305e-09,6.408305e-09,2.274088e-88,3.125660e-06,3.231362e-20,0.000000,0.000000

In [158]:
meta_df_test_X = meta_df_test[['xgb', 'lgbm', 'log_reg', 'BernoulliNB', 'RF', 'ExtraTrees']]
meta_df_test_X

,xgb,lgbm,log_reg,BernoulliNB,RF,ExtraTrees
0,4.930832e-02,1.125965e-06,7.779146e-01,4.138573e-05,0.230000,0.176667
1,1.216368e-05,9.004924e-12,3.781057e-02,1.268509e-04,0.032667,0.008000
2,1.059312e-06,4.206358e-12,5.807765e-04,4.156605e-21,0.000000,0.000667
3,2.008840e-11,1.582804e-19,1.588913e-07,9.165213e-33,0.000000,0.000000
4,1.397163e-08,2.309650e-17,8.403802e-03,9.646834e-08,0.000000,0.000667
...,...,...,...,...,...,...
50221,1.127315e-06,1.002447e-12,3.390835e-02,2.698223e-02,0.037333,0.021333
50222,4.976915e-04,1.226719e-10,2.351223e-01,2.300839e-04,0.115444,0.087333
50223,9.088521e-05,9.993779e-14,5.321311e-01,8.933855e-01,0.176667,0.110000
50224,8.021926e-03,4.051403e-09,5.585079e-01,1.442393e-04,0.116667,0.101333
50225,6.408305e-09,2.274088e-88,3.125660e-06,3.231362e-20,0.000000,0.000000

## Training a LGBM over this

In [159]:
%%time


param_grid = {
    'n_estimators': [500],
    'learning_rate': [0.1],
    'max_depth': [5]
    
}
lgbm = LGB.LGBMClassifier(objective='binary', nthreads=-1, seed=27, verbosity=2, is_imbalance=True, metric='auc')

clf = GridSearchCV(lgbm, param_grid=param_grid, cv=skf, n_jobs=-1, verbose=3, scoring='roc_auc').fit(meta_df_X, meta_df_Y)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] learning_rate=0.1, max_depth=5, n_estimators=500 ................
[CV] learning_rate=0.1, max_depth=5, n_estimators=500 ................
[CV] learning_rate=0.1, max_depth=5, n_estimators=500 ................
[CV]  learning_rate=0.1, max_depth=5, n_estimators=500, score=0.9999415631499609, total=   6.5s
[CV]  learning_rate=0.1, max_depth=5, n_estimators=500, score=0.9999997614822447, total=   7.7s
[CV]  learning_rate=0.1, max_depth=5, n_estimators=500, score=1.0, total=   8.9s

[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.8s finished

CPU times: user 3.14 s, sys: 221 ms, total: 3.36 s
Wall time: 13.6 s

In [160]:
roc_auc_score( meta_df_Y.values,clf.predict_proba(meta_df_X)[:,1])

0.9999997791502266

In [161]:
sum(clf.predict(meta_df_test_X))

144

### Saving the submission

In [162]:
c='final'
test['redemption_status'] =clf.predict_proba(meta_df_test_X)[:,1]
submission = test.loc[:,['id', 'redemption_status']]
name = "../data/submissions/meta_lgbm_"+str(c)+".csv"
submission.to_csv( name,index=False)
print("File saved!")
test['redemption_status']

File saved!

0        6.869902e-08
1        1.244540e-08
2        1.246480e-08
3        1.246480e-08
4        1.246480e-08
             ...
50221    1.105069e-08
50222    1.244510e-08
50223    1.528370e-08
50224    1.546724e-08
50225    1.246480e-08
Name: redemption_status, Length: 50226, dtype: float64

In [164]:
test[test['redemption_status'] > 0.5]

,campaign_id,coupon_id,customer_id,id,is_test,redemption_status,campaign_type,campaign_start_date,campaign_end_date,coupon_available_on_item_ids,customer_age_range,customer_marital_status,is_customer_rented,customer_family_size,customer_no_of_children,customer_income_bracket,is_common_demographic_info_available_for_customer,no_of_items_coupon_is_available_for,is_coupon_available_for_multiple_item_ids,no_of_categories_of_items_available_under_coupon,coupon_available_on_category_1,coupon_available_on_category_2,coupon_available_on_brand_1,coupon_available_on_brand_2,coupon_more_focussed_on_brand_type,popularity_of_category1,popularity_of_category2,popularity_of_brand1,popularity_of_brand2,mean_discount_on_category1,mean_discount_on_category2,mean_discount_on_brand1,mean_discount_on_brand2,no_of_times_customer_bought_category1,no_of_times_customer_bought_category2,no_of_times_customer_bought_brand1,no_of_times_customer_bought_brand2,no_of_times_customer_bought_category1_in_discount,no_of_times_customer_bought_category2_in_discount,no_of_times_customer_bought_brand1_in_discount,no_of_times_customer_bought_brand2_in_discount,has_customer_ever_bought_category1,has_customer_ever_bought_category2,has_customer_ever_bought_brand1,has_customer_ever_bought_brand2,has_customer_ever_bought_category1_in_discount,has_customer_ever_bought_category2_in_discount,has_customer_ever_bought_brand1_in_discount,has_customer_ever_bought_brand2_in_discount,average_selling_price_per_unit_of_category1_brand1_combination,average_selling_price_per_unit_of_category2_brand2_combination,average_transaction_amount_for_customer_per_item_of_category1,average_transaction_amount_for_customer_per_item_of_category2,is_customers_spending_habit_on_category1_in_favour_of_category1_brand1_combo,is_customers_spending_habit_on_category1_in_favour_of_category2_brand2_combo,campaign_duration_in_days,was_user_active_during_campaign_period,does_user_significantly_prefer_focussed_brand_type,does_user_prefer_category1_from_brand1,does_user_prefer_category1_from_brand2,does_user_prefer_any_of_brand1_brand2_for_category1,total_spends_of_customer,total_spends_category_of_customer,total_coupon_discount_claimed_by_customer,coupon_claiming_category_of_customer,most_bought_category_of_user,is_coupon_category1_same_as_customer_most_bought_category,is_brand1_same_as_most_favourite_brand_of_user_in_category1,is_brand2_same_as_second_most_favourite_brand_of_user_in_category1,is_brand2_same_as_most_favourite_brand_of_user_in_category1,is_brand1_same_as_second_most_favourite_brand_of_user_in_category1,are_the_brands_customers_favourite_brands_for_category1
361,20,671,1534,926,1,0.638557,1,2013-09-07,2013-11-16,"3463,27649,32873,1336,4313,16943,43894,18366,4...",3,1,0.0,3,1,5.0,1,69,1,1,3,0,676,-1,0,0.711382,0.000000,0.003105,0.000000,22.507003,0.000000,12.129654,0.000000,1238,0,17,0,900,0,10,0,1,0,1,0,1,0,1,0,72.914597,-1.0,68.685689,0.000000,0,1,70,0,1,0,0,0,187362.68,4,1194.24,4,1,1,0,0,0,0,0
667,19,689,389,1704,1,1.000000,1,2013-08-26,2013-09-27,"8610,33329,69233,24211,30016,33957,43057,17023...",2,1,0.0,4,2,6.0,1,72,1,1,6,0,686,-1,0,0.117204,0.000000,0.015547,0.000000,11.490816,0.000000,13.093350,0.000000,246,0,26,0,74,0,21,0,1,0,1,0,1,0,1,0,217.065908,-1.0,115.700294,0.000000,0,1,32,0,1,0,0,0,131248.71,3,1904.21,4,1,0,0,0,0,0,0
790,18,31,1070,1978,1,1.000000,0,2013-08-10,2013-10-04,"33596,41939,42796,56157,36896,71488,40715,3257...",5,0,0.0,1,0,6.0,1,4872,1,3,3,4,56,133,0,0.711382,0.072634,0.264804,0.006412,22.507003,27.890491,18.967506,31.657791,650,44,164,7,356,20,104,3,1,1,1,1,1,1,1,1,50.601550,-1.0,88.683308,128.038413,1,1,55,0,1,0,0,0,162285.14,4,3979.38,5,1,1,1,0,0,0,1
1166,18,941,566,2919,1,0.638917,0,2013-08-10,2013-10-04,"72824,72681",2,1,0.0,4,2,5.0,1,1,0,1,3,0,1180,-1,0,0.711382,0.000000,0.000621,0.000000,22.507003,0.000000,30.541615,0.000000,2089,0,43,0,1249,0,35,0,1,0,1,0,1,0,1,0,134.204073,-1.0,73.912074,0.000000,0,1,55,0,1,0,0,0,307490.77,5,6237.36,5,1,1,0,0,0,0,0
1473,22,432,378,3709,1,0.647034,0,2013-09-16,2013-10-18,"10029,53111,30902,46963,34451,46794,45061,3748...",3,1,0.0,5,3,5.0,1,48,1,1,3,0,119,-1,0,0.711382,0.000000,0.002565,0.000000,22.507003,0.000000,25.946206,0.000000,1291,0,11,0,706,0,9,0,1,0,1,0,1,0,1,0,72.877550,-1.0,57.571335,0.000000,0,1,32,0,1,0,0,0,205834.89,4,1431.89,4,1,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48726,18,32,748,124699,1,0.984613,0,2013-08-10,2013-10-04,"12028,55727,17264,28034,46293,33416,47671,6109...",4,1,0.0,3,1,8.0,1,11813,1,3,6,8,56,686,0,0.117204,0.003675,0.264804,0.015547,11.490816,26.034393,18.967506,13.093350,242,5,640,90,111,4,408,59,1,1,1,1,1,1,1,1,111.979742,-1.0,164.254731,90.904000,1,1,55,0,1,0,0,0,308723.95,5,10752.81,5,1,0,1,0,0,0,1
48925,18,501,1252,125195,1,0.638557,0,2013-08-10,2013-10-04,"45102,55975,2617,62595,28756,62594,21854,12861...",2,0,0.0,3,2,3.0,1,10,1,1,1,0,224,-1,0,0.015450,0.000000,0.000548,0.000000,15.867442,0.000000,17.259659,0.000000,330,0,19,0,159,0,7,0,1,0,1,0,1,0,1,0,107.034250,-1.0,99.462798,0.000000,0,1,55,0,1,0,0,0,296679.05,5,436.33,3,1,0,0,0,0,0,0
49150,22,518,864,125828,1,0.999486,0,2013-09-16,2013-10-18,"34936,44407,42927,3264,3544,979,65282,23340,14...",5,0,0.0,1,0,5.0,1,69,1,1,3,0,278,-1,0,0.711382,0.000000,0.018100,0.000000,22.507003,0.000000,24.820366,0.000000,1257,0,77,0,786,0,62,0,1,0,1,0,1,0,1,0,72.980151,-1.0,72.945636,0.000000,0,1,32,0,1,0,0,0,249159.25,5,3726.15,5,1,1,0,1,0,1,1
49287,18,1008,1469,126151,1,0.638557,0,2013-08-10,2013-10-04,"1646,1654,58540,71939,22591,39195,39978,42945,...",4,1,0.0,2,0,12.0,1,58,1,1,5,0,1487,-1,0,0.039999,0.000000,0.004321,0.000000,9.795598,0.000000,12.083407,0.000000,111,0,24,0,16,0,6,0,1,0,1,0,1,0,1,0,85.557081,-1.0,86.110244,0.000000,1,1,55,0,1,0,0,0,291493.40,5,1114.18,4,1,0,0,1,0,1,1
49462,24,42,1257,126633,1,0.999971,1,2013-10-21,2013-12-20,"64074,56715,11489,36119,60336,9925,52873,21547...",4,0,0.0,1,0,5.0,1,1588,1,3,3,5,56,1101,0,0.711382,0.002414,0.264804,0.007418,22.507003,2.868119,18.967506,28.619771,1606,0,133,34,970,0,85,20,1,0,1,1,1,0,1,1,50.601550,-1.0,72.801973,0.000000,1,1,60,0,1,0,0,0,216844.88,5,4161.47,5,1,1,1,0,0,0,1

## Training a XGB over this

In [167]:
%%time


param_grid = {
    'n_estimators': [500],
    'learning_rate': [0.1],
    'max_depth': [5]
    
}
lgbm = LGB.LGBMClassifier(objective='binary', nthreads=-1, seed=27, verbosity=2, is_imbalance=True, metric='auc')

clf = GridSearchCV(lgbm, param_grid=param_grid, cv=skf, n_jobs=-1, verbose=3, scoring='roc_auc').fit(meta_df_X, meta_df_Y)

Fitting 3 folds for each of 1 candidates, totalling 3 fits
[CV] learning_rate=0.1, max_depth=5, n_estimators=500 ................
[CV] learning_rate=0.1, max_depth=5, n_estimators=500 ................
[CV] learning_rate=0.1, max_depth=5, n_estimators=500 ................
[CV]  learning_rate=0.1, max_depth=5, n_estimators=500, score=0.9999415631499609, total=   6.0s
[CV]  learning_rate=0.1, max_depth=5, n_estimators=500, score=0.9999997614822447, total=   7.2s
[CV]  learning_rate=0.1, max_depth=5, n_estimators=500, score=1.0, total=   8.2s

[Parallel(n_jobs=-1)]: Done   3 out of   3 | elapsed:    9.2s finished

CPU times: user 3.14 s, sys: 120 ms, total: 3.26 s
Wall time: 12.9 s

In [168]:
roc_auc_score( meta_df_Y.values,clf.predict_proba(meta_df_X)[:,1])

0.9999997791502266

In [169]:
sum(clf.predict(meta_df_test_X))

144

### Saving the submission

In [170]:
c='final'
test['redemption_status'] =clf.predict_proba(meta_df_test_X)[:,1]
submission = test.loc[:,['id', 'redemption_status']]
name = "../data/submissions/meta_xgb_"+str(c)+".csv"
submission.to_csv( name,index=False)
print("File saved!")
test['redemption_status']

File saved!

0        6.869902e-08
1        1.244540e-08
2        1.246480e-08
3        1.246480e-08
4        1.246480e-08
             ...
50221    1.105069e-08
50222    1.244510e-08
50223    1.528370e-08
50224    1.546724e-08
50225    1.246480e-08
Name: redemption_status, Length: 50226, dtype: float64

# Creating an ensemble of XGB, LGB, Meta XGB, Meta LGBM, RF and Extra Trees

In [172]:
xgb = pd.read_csv("../data/submissions/submission_after_modeling_xgbfinal.csv")
lgbm = pd.read_csv("../data/submissions/submission_after_modeling_lgb_final.csv")
meta_xgb = pd.read_csv("../data/submissions/meta_xgb_final.csv")
meta_lgbm = pd.read_csv("../data/submissions/meta_lgbm_final.csv")
RF = pd.read_csv("../data/submissions/submission_after_modeling_RF_final.csv")
ExtraTrees = pd.read_csv("../data/submissions/submission_after_modeling_ExtraTrees_final.csv")

In [173]:
ensembled = meta_xgb.copy()

In [175]:
ensembled['redemption_status'] = ensembled['redemption_status']*0.30
ensembled['redemption_status'] = ensembled['redemption_status']+meta_lgbm['redemption_status']*0.30+xgb['redemption_status']*0.1+lgbm['redemption_status']*0.1+RF['redemption_status']*0.1+ExtraTrees['redemption_status']*0.1

In [177]:
ensembled[ensembled.redemption_status > 0.5]

           id  redemption_status
667      1704           0.816928
790      1978           0.644602
2085     5224           0.650290
2645     6577           0.751112
3603     8968           0.650389
...       ...                ...
48146  123136           0.798120
48503  124134           0.695733
48726  124699           0.603610
49150  125828           0.614934
49462  126633           0.590455

[114 rows x 2 columns]

### Saving the ensembled solution

In [178]:
c='final'
name = "../data/submissions/submission_stacked_and_ensembled_"+str(c)+".csv"
ensembled.to_csv( name,index=False)
print("File saved!")

File saved!